### ISSUE TITLE
Note: Requires VLT CLI 3.1.0 or higher

### ISSUE THREAD

**Issue by yan-kisen** [Cognifide/Maven-Vault-Checkout-Plugin#2]
FYI this tool will not work correctly in combination with VLT CLI < 3.1.0 when they stopped storing plaintext passwords in ~/.vault/auth.xml

[Apache Jackrabbit FileVault - 3.1.0 - Release Notes](https://www.apache.org/dist/jackrabbit/filevault/3.1.0/RELEASE-NOTES.txt)

I had been using vault-cli-2.4.34 and couldn't `update` nor `commit` changes to the repository with the following error:

```
Connecting via JCR remoting to http://192.168.99.100:4504/crx/server
[ERROR] commit: com.day.jcr.vault.vlt.VltException: Unable to mount filesystem
caused by: javax.jcr.RepositoryException: Unauthorized
  caused by: org.apache.jackrabbit.webdav.DavException: Unauthorized
```

Everything works perfectly after updating to 3.1.16

**Comment by lmatyja** [comment]
Hi yan-kisen, thanks for your feedback. I will take a look on this issue.

**Comment by yan-kisen** [comment]
It's not an issue, more of a comment for anyone else experiencing the same thing.

Perhaps make a note in the README?
