### ISSUE TITLE
Support line ending configuration for checkout

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/Maven-Vault-Checkout-Plugin#4]
Originally raised in the Cognifide Jira (CQMA-353)

> When using `vltco` on Windows, the plugin sets Windows line endings on every processed file. If the repository has unix line endings, the user has to change that endings back to lf.
> 
> Vltco uses FileUtils that uses default system line endings
> ```
> FileUtils.writeLines(file, CharEncoding.UTF_8, lines); (CleanHelper.java line:51)
> ```
> 
> however there is an extended method that allows the user to set line endings
> 
> ```
> FileUtils.writeLines(File file, String encoding, Collection<?> lines, String lineEnding)
> ```

**Comment by toniedzwiedz** [comment]
Line separators can be enforced from the command line

    mvn vltco:clean-checkout -Dline.separator=$'\n'

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
